// import {API_URL_BOOLEAN_OPERATOR_IDENTIFIER} from './apiUrlIdentifier'
export const API_URL_AND_OPERATOR = 'AND' 
// + `${API_URL_BOOLEAN_OPERATOR_IDENTIFIER}`;
export const API_URL_OR_OPERATOR = 'OR'
//  + `${API_URL_BOOLEAN_OPERATOR_IDENTIFIER}`;
export const API_URL_NOT_OPERATOR = 'NOT'
//  + `${API_URL_BOOLEAN_OPERATOR_IDENTIFIER}`;
